import { redirect } from "next/navigation";

export const metadata = {
  title: "Vino| Blog ",
  description: "Generated by create next app",
};

export default function BlogPage() {
  redirect("blog/order_by_tag")
}
