import { redirect } from 'next/navigation';

export const metadata = {
  title: "Vino| About me",
  description: "Generated by create next app",
};


export default function Home() {
  redirect("about")
}
